spring:
  application:
    name: mar-de-beleza-system
    security:
      jwt:
        secret-key: ${JWT_SECRET}
  profiles:
    active: dev
spring-doc:
  paths-to-match: /api/v1/**
  swagger-ui:
    use-root-path: true